from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BACKEND_ROOT.parent
WORKDIR = PROJECT_ROOT / "workdir"
SAMPLES_DIR = PROJECT_ROOT / "samples"

TARGET_SAMPLE_RATE = 44_100
TARGET_CHANNELS = 2
INPUT_PEAK_DBFS = -1.0
OUTPUT_PEAK_DBFS = -0.5
MAX_INPUT_DURATION_S = 15 * 60
MIN_BPM_CONFIDENCE = 0.5
BPM_BEAT_MATCH_TOLERANCE = 0.08
MIN_TRACK_DURATION_S = 60
SILENCE_GAP_LIMIT_S = 30
